server:
  port: 9999

spring:
  cloud:
    gateway:
      globalcors:
        # Crucial: This ensures CORS is handled before the filter logic
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service
          uri: lb://PRODUCTS-SERVICE
          predicates:
            # Combined /api/v1/carousel** to match both /carousel and /carousel/
            - Path=/api/v1/products/**, /api/v1/catalogues/**, /api/v1/comments/**, /api/v1/rating/**, /api/v1/reviews/**, /product-images/**, /api/v1/carousel/**, /api/v1/carousel**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - AuthenticationFilter

jwt:
  secret: "4f6e63652075706f6e20612074696d6520696e20612067616c617879206661722061776179"