server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/api/v1/products/**, /api/v1/catalogues/**, /api/v1/comments/**, /api/v1/rating/**, /api/v1/reviews/**, /product-images/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - AuthenticationFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

jwt:
  secret: "4f6e63652075706f6e20612074696d6520696e20612067616c617879206661722061776179"