server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter

jwt:
  secret: "4f6e63652075706f6e20612074696d6520696e20612067616c617879206661722061776179"