server:
  port: 9002

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:collo}
    password: ${SPRING_DATASOURCE_PASSWORD:Kipkirui92?}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Kafka Producer Settings (Added)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      # Key is usually a String (like Order ID)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Value is your Order DTO converted to JSON
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer